name: CI/CD Unit testing
on: [push, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Run Unit tests
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.4